set_property SRC_FILE_INFO {cfile:{C:/Users/hp/Desktop/Integrated Systems Design/PAgarwal_lab0/PAgarwal_lab0.srcs/constrs_1/imports/PAgarwal_lab0/Basys3_Master.xdc} rfile:../../../PAgarwal_lab0.srcs/constrs_1/imports/PAgarwal_lab0/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
